export const AppPages = {
  HOME: "/",
  LOGIN: "/login",
  SIGN_UP: "/signup",
  FIND_EMAIL: "/find-email",
  FIND_PASSWORD: "/find-password",
  EDIT_PASSWORD: "/edit-password",
  CUSTOMER_ORDER_LIST: "/customer/order",
  CUSTOMER_CREATE_ORDER: "/customer/order/create",
  FACTORY_ORDER_LIST: "/factory/order",
  FACTORY_NEW_ORDER_LIST: "/factory/order/new",
  ORDER_DETAIL: "/order",
  ACQUIRER: "/acquier",
  MY_PAGE: "/mypage",
};
